# Generated by Django 2.0.7 on 2021-03-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60)),
                ('postalCode', models.CharField(max_length=60)),
                ('sqrAcres', models.DecimalField(decimal_places=3, max_digits=1000)),
            ],
        ),
    ]
