# Generated by Django 3.1.7 on 2021-04-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210415_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankowner',
            name='ownerId',
        ),
        migrations.RemoveField(
            model_name='companyowner',
            name='ownerId',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.RemoveField(
            model_name='land',
            name='neighborhoodName',
        ),
        migrations.RemoveField(
            model_name='ownsrelation',
            name='land',
        ),
        migrations.RemoveField(
            model_name='ownsrelation',
            name='ownerID',
        ),
        migrations.RemoveField(
            model_name='personowner',
            name='ownerId',
        ),
        migrations.DeleteModel(
            name='BankOwner',
        ),
        migrations.DeleteModel(
            name='CompanyOwner',
        ),
        migrations.DeleteModel(
            name='Land',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='OwnsRelation',
        ),
        migrations.DeleteModel(
            name='PersonOwner',
        ),
    ]
