# Generated by Django 3.1.7 on 2021-04-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210415_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='costPerMonth',
            field=models.DecimalField(decimal_places=2, default=10.15, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renter',
            name='leaseDuration',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
